In [19]:
an_ball=75
an_bat=25

In [21]:
an_ball

75

In [13]:
b=(1,2,2,3,8)

In [14]:
b.index(8)

4

In [16]:
b=[1,2,5,4]

In [17]:
b?

In [23]:
?b

In [24]:
print?

In [25]:
a=2;b=5;c=9
a

2

In [26]:
b

5

In [27]:
c

9

In [57]:
file_handle=["foo","","vamsee"]
results = []
for i in file_handle:
    #results.append(i)
 # keep the empty lines for now
    if len(i) == 0:
        continue
results.append(i.replace("vamsee", "bar"))

In [58]:
results

['bar']

In [61]:
a="FOO"

In [62]:
a.casefold()

'foo'

In [63]:
a=[1,2,3]

In [64]:
b=a

In [65]:
c=list(a)

In [66]:
a is b 

True

In [67]:
a is not c

True

In [68]:
c

[1, 2, 3]

In [69]:
a

[1, 2, 3]

In [70]:
b

[1, 2, 3]

In [75]:
a= ["foo", 2, [4, 5]]

In [79]:
a[2][1]=6

In [80]:
a[2][1]

6

In [81]:
a_list = ["foo", 2, [4, 5]]

In [82]:
a[2][1]=(6,7)

In [83]:
a[2][1]

(6, 7)

In [84]:
a[2][1]=5

In [85]:
a[2][1]

5

In [86]:
t=(4,5,8,["vishal"])

In [87]:
t[3]="ramu"

TypeError: 'tuple' object does not support item assignment

In [88]:
a='''vishal'''

In [89]:
a

'vishal'

In [95]:
a="""It may surprise you that this string c actually 
"""#contains four lines of text; the line
#breaks after  and after lines are included i
#n the string. We can count the new line
#characters with the count method on c:"""

In [96]:
a

'It may surprise you that this string c actually \n'

In [97]:
a.count("\n")

1

In [98]:
a = "this is a string"
a[10] = "f"

TypeError: 'str' object does not support item assignment

In [100]:
a = 5.6
s = str(a)
print(s)
type(s)

5.6


str

In [104]:
#sum of tuple
a=tuple(map(int,input("enter the number:").split(" ")))
s=0
for i in a:
    s=s+i
print(s)

enter the number:1 2 3 4 5 6 7 8 9 10
55


In [114]:
a=tuple(input("enter the number:").split(" "))
print(a)
b="".join(a)
print(b)

enter the number:vishal uh3ufh
('vishal', 'uh3ufh')
vishaluh3ufh


In [119]:
a=tuple(map(int,input("enter the number:").split(" ")))


enter the number:4 5 7 8 6


In [120]:
4 in a

True

In [122]:
a=tuple(map(int,input("enter the number:").split(" ")))
b=max(a)
c=min(a)

enter the number:4 7 8 5 1 2 3 6 9


In [123]:
b

9

In [124]:
c

1

In [125]:
a=tuple(input("enter the number:").split(" "))
b=sorted(a)

enter the number:vishal apple zebra yolk


In [126]:
b

['apple', 'vishal', 'yolk', 'zebra']

In [128]:
a=tuple(map(int,input("enter the number:").split()))
b=list(a)

enter the number:4 7 8 5 1 2 3 6 9


In [129]:
b

[4, 7, 8, 5, 1, 2, 3, 6, 9]

In [131]:
a=tuple(map(int,input("enter the number:").split(" ")))
p=1
for i in a:
    p=p*i
print(p)
    

enter the number:1 2 3 4 5
120


In [134]:
a=tuple(map(int,input("enter the number:").split(" ")))
b=tuple(map(int,input("enter the number (of same lenght as above):").split(" ")))
for i in a:
    for j in b:
        if i==j:
            c=i+j
print(c)


enter the number:1 2 4 5
enter the number (of same lenght as above):2 3 5 6


TypeError: can only join an iterable

In [ ]:
num_entries = int(input("Enter the number of entries you want to add: "))
user_dict = {}
for i in range(num_entries):
    key = input("Enter key: ")
    value = input("Enter value: ")
    user_dict[key] = value
print(user_dict.values())

In [ ]:
d={}



In [ ]:
?d

In [3]:
tup = 4, 5, 6

In [5]:
tup

(4, 5, 6)

In [6]:
tuple([4, 0, 2])

(4, 0, 2)

In [7]:
tup = tuple('string')

In [8]:
tup

('s', 't', 'r', 'i', 'n', 'g')

In [9]:
tup=(4,5,7,8)

In [10]:
tup.append(8)

AttributeError: 'tuple' object has no attribute 'append'

In [12]:
(4, None, 'foo') + (6, 0) + ('bar',)

(4, None, 'foo', 6, 0, 'bar')

In [13]:
 (4, None, 'foo') + (6, 0) + ('bar',)

(4, None, 'foo', 6, 0, 'bar')

In [21]:
 (4, None, 'foo') + (6, 0) + (1,)

(4, None, 'foo', 6, 0, 1)

In [31]:
tup=(4,5,4)

In [32]:
a, b, c= tup

In [33]:
a,b,c

(4, 5, 4)

In [34]:
a, b = 1, 2

In [35]:
a,b=b,a

In [36]:
a

2

In [37]:
b

1

In [38]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [39]:
for a, b, c in seq:
    print(f'a={a}, b={b}, c={c}')

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [40]:
values = 1, 2, 3, 4, 5
a, b, *rest = values

In [41]:
rest


[3, 4, 5]

In [42]:
a={1,4,5}

In [43]:
b={9,6,4,3}

In [52]:
a|=b

In [53]:
a

{1, 3, 4, 5, 6, 9}

In [66]:
a=(9,2,1,2,3,5,4,4)

In [79]:
a[7]

4

In [80]:
b = ["saw", "small", "He", "fox", "six"]
b.sort(key=len)
b


['He', 'saw', 'fox', 'six', 'small']

In [92]:
tuples= zip(range(5), reversed(range(5)))

In [93]:
tuples

In [94]:
mapping = dict(tuples)

In [95]:
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

In [96]:
a=[1,2,3]

In [97]:
b=['a','b','c']

In [99]:
c=zip(a,b)

In [100]:
c

In [104]:
list(c)

TypeError: 'zip' object is not callable

In [114]:
numbers = [1, 2, 3]
letters = ['a', 'b', 'c']
zipped = zip(numbers, letters)
tuple(zipped)

((1, 'a'), (2, 'b'), (3, 'c'))

In [113]:
numbers = [1, 2, 3]
letters = ['a', 'b', 'c']
zipped = zip(numbers, letters)
tuple(zipped)


((1, 'a'), (2, 'b'), (3, 'c'))

In [109]:
zipped

In [112]:
s1 = {2, 3, 1}
s2 = {'b', 'a', 'c'}
list=(zip(s1, s2))
print(tuple(list))

((1, 'c'), (2, 'a'), (3, 'b'))


In [119]:
a = ("John", "Charles", "Mike","Mike")
b = ("Jenny", "Christy", "Monica","Monica")
x = zip(a, b)
print(set(x))

{('Mike', 'Monica'), ('Charles', 'Christy'), ('John', 'Jenny')}


In [122]:
words = ["apple", "Mnago","bat", "bar", "atom", "book"]
by_letter = {}
for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else:
        by_letter[letter].append(word)
by_letter

{'a': ['apple', 'atom'], 'M': ['Mnago'], 'b': ['bat', 'bar', 'book']}

In [2]:
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [50]:
strings = ["a", "as", "bat", "car", "dove", "python"]

In [51]:
[x.upper() for x in strings if len(x) > 2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [52]:
unique_lengths = {len(s) for s in strings}

In [53]:
unique_lengths

{1, 2, 3, 4, 6}

In [54]:
set(map(max, strings))

{'a', 'r', 's', 't', 'v', 'y'}

In [55]:
loc_mapping = {value: index for index, value in enumerate(strings)}

In [56]:
loc_mapping 

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [80]:
 all_data = [["John", "Emily", "Michael", "Mary", "Steven"],
            ["Maria", "Juan", "Javier", "Natalia", "Pilar"]]

In [81]:
names_of_interest = []

In [82]:
for names in all_data:
    enough_as = [name for name in names if name.count("a") >= 2]
    names_of_interest.extend(enough_as)

In [83]:
names_of_interest 

['Maria', 'Natalia']

In [63]:
fruits = ['apple', 'banana', 'cherry']

cars = ['Ford', 'BMW', 'Volvo']

fruits.extend(cars)

print(fruits)

['apple', 'banana', 'cherry', 'Ford', 'BMW', 'Volvo']


In [84]:
#nested list
result = [name for names in all_data for name in names
if name.count("a") >= 2]

In [85]:
result

['Maria', 'Natalia']

In [86]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [93]:
flattened = [x for tup in some_tuples for x in tup if x % x == 0 and x % 1 == 0 and x % y != 0]

NameError: name 'y' is not defined

In [94]:
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [125]:
a=[x for x in range(2, 20) if all(x % y for y in range(2, x//2))]

In [126]:
a

[2, 3, 4, 5, 7, 11, 13, 17, 19]

In [114]:
flattened = []
for tup in some_tuples:
    for x in tup:
        flattened.append(x)

In [115]:
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [118]:
2%1

0

In [133]:
states = [" Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda",
        "south carolina##", "West virginia?"]


In [144]:
states = [" Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda", "south carolina##", "West virginia?"]
import re

def clean_strings(states):
    result = []
    for value in states:
        value = value.strip()
        value = re.sub("[!#?]", "", value)
        value = value.title()
        result.append(value)
    return result


cleaned_states = clean_strings(states)
print(cleaned_states)


['Alabama', 'Georgia', 'Georgia', 'Georgia', 'Florida', 'South Carolina', 'West Virginia']


In [145]:
import numpy as np

In [146]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [147]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [148]:
import itertools

In [31]:
#The “bare” slice [:] will assign to all values in an array:
import numpy as np
arr=np.arange(10)


In [32]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[5:8]

array([5, 6, 7])

In [34]:
arr[5:8]=12

In [35]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [36]:
arr_slice=arr[5:8]

In [37]:
arr_slice

array([12, 12, 12])

In [39]:
arr_slice[1]=12345

In [40]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [41]:
#The “bare” slice [:] will assign to all values in an array
arr_slice[:] = 64

In [42]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [43]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [44]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
old_values = arr3d[0].copy()

In [50]:
arr3d[0] = 42

In [51]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[0] = old_values

In [53]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
 x = arr3d[1]

In [55]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [57]:
"""Note that in all of these cases where subsections of the array have been selected, the
returned arrays are views."""
x[0]

array([7, 8, 9])

In [59]:
import numpy as np
a = np.arange(2, 10, dtype=float).reshape(2, 4)

In [60]:
a

array([[2., 3., 4., 5.],
       [6., 7., 8., 9.]])

In [61]:
#Boolean indexing
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [62]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
[-12, -4], [3, 4]])

In [63]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [64]:
data 

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [65]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

In [66]:
data[names=="Bob"]

array([[4, 7],
       [0, 0]])

In [67]:
"""Fancy Indexing
Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.
Suppose we had an 8 × 4 array:"""
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i

In [68]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [69]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [70]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [71]:
import numpy as np

# Create a 3x3 identity array with string elements
identity_array = np.array([[str(int(i == j)) for j in range(3)] for i in range(3)])

print(identity_array)



[['1' '0' '0']
 ['0' '1' '0']
 ['0' '0' '1']]


In [72]:
m=np.identity(3)

In [73]:
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])