In [37]:
import numpy as np

In [38]:
ar=np.arange(34)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [39]:
arr=np.array([[1,2],[3,5]])
arr

array([[1, 2],
       [3, 5]])

In [40]:
arr.shape

(2, 2)

In [41]:
arr.dtype

dtype('int32')

In [42]:
list1=[1,2,3,4,5,6,7,8,9,0]
arr=np.array(list1)
print(arr)

[1 2 3 4 5 6 7 8 9 0]


In [43]:
arr.ndim

1

In [44]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
arr=np.zeros(5)
print(arr)
arr.dtype

[0. 0. 0. 0. 0.]


dtype('float64')

In [120]:
help(np.arange)
help(np.asarray)
help(np.ones)
help(np.ones_like)
help(np.reshape)
help(np.identity)
help(np.empty)
help(np.empty_like)
help(np.full)
help(np.full_like)
help(np.eye)
help(np.identity)
type(arr)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

numpy.ndarray

In [58]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [59]:
np.reshape(a, 6, order='F')


array([1, 4, 2, 5, 3, 6])

In [62]:
np.reshape(a, 6, order='c')


array([1, 2, 3, 4, 5, 6])

In [78]:
arr=np.empty(7)
arr

array([0., 0., 0., 0., 0., 0., 0.])

In [80]:
au=np.empty_like(arr)
au

array([0., 0., 0., 0., 0., 0., 0.])

In [93]:
c=np.full((2,2),[1,3])
c

array([[1, 3],
       [1, 3]])

In [98]:
x = np.arange(6, dtype=int)
print(np.full_like(x, 1))
np.full_like(x, 0.1)

[1 1 1 1 1 1]


array([0, 0, 0, 0, 0, 0])

In [104]:
np.eye(3,)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
arr=np.array([11,2,3,4,5,6,7,7,7])
arr[1:4]

array([2, 3, 4])

In [109]:
c=np.copy(arr[1:4])
c

array([2, 3, 4])

In [112]:
c==4

array([False, False,  True])

In [113]:
c+c

array([4, 6, 8])

In [118]:
arr=np.array([[1,2,4],[3,5,8],[7,6,23]])
arr

array([[ 1,  3,  7],
       [ 2,  5,  6],
       [ 4,  8, 23]])

In [117]:
arr=np.array([[1,2,4],[3,5,8]])
arr.T

array([[1, 3],
       [2, 5],
       [4, 8]])