In [46]:
#import random as rm
from numpy import random
mylist = ["Yethishwar", "Omair Ahmed","Srikar", "Suresh", "Satish", "Kiran", "Siddhartha"]
random_integer = rm.randint(0,1000)
random_choice = rm.choice(mylist)
print(random_choice)
print(random_integer)
shuffle_list = [12,32,43,55,43,23,11]
rm.shuffle(shuffle_list)
print(shuffle_list)

Siddhartha
165
[11, 12, 23, 32, 43, 55, 43]


In [48]:
import numpy as np

# Creating a 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print(arr1d[0])  # Output: 1
print(arr2d[1, 1])  # Output: 5

# Performing operations
sum_arr1d = np.sum(arr1d)  # Sum of all elements in arr1d
print(sum_arr1d)  # Output: 15


1
5
15


In [51]:
import numpy as np

# Generating random integers
random_integers = np.random.randint(1, 100, size=5)  # 5 random integers between 1 and 100
print(random_integers)

# Generating random numbers from a normal distribution
random_normal = np.random.normal(0, 1, size=(3, 3))  # 3x3 array of random numbers with mean 0 and standard deviation 1
print(random_normal)


[25 42 24  3 40]
[[ 0.21026368 -1.08190233  0.15314077]
 [ 0.03576534  0.98132162  0.24876478]
 [ 0.23606997  0.14212534 -0.5525276 ]]


In [52]:
import numpy as np

# Creating arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
result_addition = arr1 + arr2
print("Element-wise addition:")
print(result_addition)

# Element-wise multiplication
result_multiplication = arr1 * arr2
print("\nElement-wise multiplication:")
print(result_multiplication)

# Matrix multiplication
result_matrix_multiplication = np.dot(arr1, arr2)
print("\nMatrix multiplication:")
print(result_matrix_multiplication)


Element-wise addition:
[[ 6  8]
 [10 12]]

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]
